package ddl

import (
	"fmt"
	"strings"

	"goscan/pkg/config"
)

// LegacyVolcEngineBillTable is what the VolcEngine bill table was called before
// the names were lined up with logpipe / tracepipe / metricpipe.
const LegacyVolcEngineBillTable = "volcengine_bill_details"

// legacyDistributedSuffix is the suffix the Distributed tables used to carry.
// They go by the base name now, so every *_distributed table an older release
// created is left over on a cluster and nothing reads it any more.
const legacyDistributedSuffix = "_distributed"

// DropLegacySQL renders the one-off script that removes the tables the previous
// naming left behind. Like Render it only prints; applying it is the operator's
// call, because one of those tables holds rows.
//
// A table the config still names is left alone: an operator who pinned
// `bill_table: volcengine_bill_details` is using that table, not carrying it
// over from an old release.
func DropLegacySQL(cfg *config.Config, o Options) string {
	var b strings.Builder
	b.WriteString("-- Generated by `goscan --drop-legacy`. A one-off migration, not part of `--ddl`.\n")
	b.WriteString("-- Run it once, after `--ddl` has created the tables under the new names, on a\n")
	b.WriteString("-- deployment upgraded from the release that suffixed Distributed tables with\n")
	b.WriteString("-- _distributed and called the VolcEngine table volcengine_bill_details.\n")

	volcTable := VolcEngineBillTableName(cfg.GetVolcEngineConfig())
	if volcTable != LegacyVolcEngineBillTable {
		from, to := LegacyVolcEngineBillTable, volcTable
		if o.Cluster != "" {
			from, to = from+"_local", to+"_local"
		}
		b.WriteString("--\n")
		b.WriteString("-- A Distributed table stores nothing, so dropping the *_distributed ones only\n")
		b.WriteString("-- removes an unused shell. The VolcEngine table is different: it holds the\n")
		b.WriteString("-- rows themselves. goscan pulls them again on the next run (as far back as\n")
		b.WriteString("-- max_historical_months), but to keep them instead of re-fetching, rename it\n")
		b.WriteString("-- rather than drop it — and then leave that DROP out below:\n")
		fmt.Fprintf(&b, "--   RENAME TABLE `%s`.`%s` TO `%s`.`%s`%s;\n",
			o.Database, from, o.Database, to, onCluster(o))
	}

	names := legacyTables(cfg, o)
	if len(names) == 0 {
		b.WriteString("\n-- Nothing to drop: this config names no table the old release left behind.\n")
		return b.String()
	}

	b.WriteString("\n")
	for _, name := range names {
		fmt.Fprintf(&b, "DROP TABLE IF EXISTS `%s`.`%s`%s;\n", o.Database, name, onCluster(o))
	}
	return b.String()
}

// legacyTables lists the tables the old naming created that the current config
// no longer uses, Distributed shell before the local table under it.
func legacyTables(cfg *config.Config, o Options) []string {
	volcTable := VolcEngineBillTableName(cfg.GetVolcEngineConfig())

	var names []string
	for _, t := range Tables(cfg) {
		// The name this table went by in the old release. Only the VolcEngine
		// one was renamed; the Alibaba Cloud tables kept theirs, and there all
		// that changed is that the Distributed table moved onto the base name.
		old := t.Name
		if t.Name == volcTable && volcTable != LegacyVolcEngineBillTable {
			old = LegacyVolcEngineBillTable
		}

		if o.Cluster == "" {
			// Single node: one table, so only a rename leaves anything behind.
			if old != t.Name {
				names = append(names, old)
			}
			continue
		}

		names = append(names, old+legacyDistributedSuffix)
		if old != t.Name {
			names = append(names, old+"_local")
		}
	}
	return names
}

func onCluster(o Options) string {
	if o.Cluster == "" {
		return ""
	}
	return fmt.Sprintf(" ON CLUSTER `%s`", o.Cluster)
}
